FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

#------------------------
# General setup
#------------------------
RUN apt-get update \
    && apt-get install -y lsb-release \
    wget 

#------------------------
# ROS Install
#------------------------

#------------------------
# DLS HyQ Install
#------------------------